articles/urls.py
from django.urls import path
from . import views
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

app_name="articles"
urlpatterns = [
    path('',views.list,name="list"),
    path('<slug>',views.detail,name="detail"),
]
urlpatterns+=staticfiles_urlpatterns()

articles/models.py
from django.db import models

class Articles(models.Model):
    title=models.CharField(max_length=100)
    slug =models.SlugField()
    body=models.TextField()
    date=models.DateTimeField(auto_now_add=True)
    image=models.ImageField(default='default.jpg', blank=True)


    def __str__(self):
        return self.title
    
    def snippet(self):
        return self.body[ :50]+'...'

articles/views.py
from django.shortcuts import render
from . import models
from django.shortcuts import HttpResponse

def list(request):
    articles=models.Articles.objects.all()
    arg={'articles':articles}
    return render(request,'articles/list.html',arg)

def detail(request,slug):
    # return HttpResponse(slug)
    arti=models.Articles.objects.get(slug=slug)
    return render(request,'articles/detail.html',{'arti':arti})

articles/templates/articles/list.html
{% load static %}
<html lang="en" dir="ltr">
    <head>
        <meta charset="utf-8">
        <title>about</title>
        <link rel="stylesheet" href="{% static 'style.css'%}">
    </head>

    <body>
        <h1><a href="{% url 'articles:list' %}">list of articles </a></h1>
        {% for x in articles%}
        <h3><a href={% url 'articles:detail' slug=x.slug %}>{{x.title}}</a><h3>
        <p>{{x.date}}</p>
        <p>{{x.snippet}}</p>
        {% endfor %}
    </body>

</html>